apiVersion: apps/v1
kind: Deployment
metadata:
  name: irisops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: irisops-app
  template:
    metadata:
      labels:
        app: irisops-app
    spec:
      containers:
      - name: irisops-app
        image: us-central1-docker.pkg.dev/irisops/irisops-repo/irisops-app:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: irisops-service
spec:
  selector:
    app: irisops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer